format = """
[](fg:#e06c75)\
$username\
[](bg:#97c277 fg:#e06c75)\
$directory\
[](fg:#97c277 bg:#61afef)\
$git_branch\
$git_status\
[](fg:#61afef bg:#c678dd)\
$c\
$python\
$lua\
$nodejs\
$rust\
[](fg:#c678dd bg:#e4bf7a)\
$cmd_duration\
$docker_context\
[](fg:#e4bf7a bg:#abb2bf)\
$time\
[ ](fg:#abb2bf)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#e06c75"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#97c277 fg:#282c34"

format = "[ $path ]($style)"
# truncation_length = 6
# truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~/Documents" = "󱔗 "
"~/Downloads" = " "
"~/Music" = " "
"~/Pictures" = " "
"~/.config" = " "
"~" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#c678dd"
format = '[[ $symbol ($version) ](fg:#282c34 bg:#c678dd)]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[git_branch]
symbol = ""
style = "bg:#5c6370"
format = '[[ $symbol $branch ](fg:#282c34 bg:#61afef)]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[[($all_status$ahead_behind )](fg:#282c34 bg:#61afef)]($style)'
disabled = false

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#3e4452 bg:#c678dd)]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](fg:#282c34 bg:#c678dd)]($style)'

[python]
symbol = " "  
style = "bg:#c678dd"
format = '[[ $symbol ($version) ](fg:#282c34 bg:#c678dd)]($style)'

[lua]
symbol = " "  
style = "bg:#c678dd"
format = '[[ $symbol ($version) ](fg:#282c34 bg:#c678dd)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#282c34"
format = '[[ ♥ $time ](fg:#282c84 bg:#abb2bf)]($style)'

[package]
disabled = true

[cmd_duration]
min_time = 1_000
show_notifications = true
min_time_to_notify = 90_000
style = "fg:#3e4452 bg:#e4bf7a"
format = '[ $duration ]($style)'